const courses = [
    {
      title: "React for Beginners",
      provider: "TechNova",
      price: "$50",
      category: "Web Development",
      level: "Beginner",
      skills: ["React", "JavaScript"],
      image: "https://ashokitech.com/uploads/course/react-js-online-training.png",
    },
    {
      title: "Advanced Node.js",
      provider: "WebSolutions",
      price: "$120",
      category: "Backend Development",
      level: "Advanced",
      skills: ["Node.js", "MongoDB", "Express"],
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgybN-Rye6rteNO0AaiAUha4FEFPwm6xDVGg&s",
    },
    {
      title: "UI/UX Design Fundamentals",
      provider: "Cloudify",
      price: "$75",
      category: "Design",
      level: "Intermediate",
      skills: ["Figma", "Sketch"],
      image: "https://d3f1iyfxxz8i1e.cloudfront.net/courses/course_image/8c972fed5118.jpeg",
    },
    {
      title: "Python Data Science Bootcamp",
      provider: "DataMinds",
      price: "Free",
      category: "Data Science",
      level: "Intermediate",
      skills: ["Python", "Pandas", "NumPy", "Matplotlib"],
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5Ku63EZbB6Y0Yl6JZDGl1LkSrcfXSZwdYEA&s",
    },
    {
      title: "iOS App Development with Swift",
      provider: "AppleTech",
      price: "$150",
      category: "Mobile Development",
      level: "Beginner",
      skills: ["Swift", "Xcode", "iOS SDK"],
      image: "https://img-b.udemycdn.com/course/750x422/1778502_f4b9_12.jpg",
    },
    {
      title: "Machine Learning Fundamentals",
      provider: "AI Academy",
      price: "$180",
      category: "Artificial Intelligence",
      level: "Intermediate",
      skills: ["Python", "TensorFlow", "Scikit-learn"],
      image: "https://i.ytimg.com/vi/hmOiINgO6tA/maxresdefault.jpg",
    },
    {
      title: "Cybersecurity Essentials",
      provider: "SecureNet",
      price: "Free",
      category: "IT Security",
      level: "Beginner",
      skills: ["Network Security", "Cryptography", "Ethical Hacking"],
      image: "https://training.linuxfoundation.org/wp-content/uploads/2023/03/LFC108_sg.png",
    },
    {
      title: "Full Stack JavaScript Development",
      provider: "CodeMasters",
      price: "$250",
      category: "Web Development",
      level: "Advanced",
      skills: ["JavaScript", "React", "Node.js", "MongoDB", "Express"],
      image: "https://developerguru.in/images/courses/mern_stack.gif",
    }
  ];

  export default courses;