const jobsData = {
    jobs: [
      {
        id: "001",
        title: "Senior Full Stack Developer at TechNova",
        company: "TechNova",
        category: "Web Development",
        salary: "$120k/year",
        location: "San Francisco, CA",
        jobType: "Full-time",
        description: "TechNova is seeking a talented Senior Full Stack Developer to join our innovative team. You'll work on cutting-edge projects using the latest technologies to build scalable web applications.",
        level: "Senior",
        technicalSkills: ["React", "Node.js", "MongoDB", "AWS"]
      },
      {
        id: "002",
        title: "Frontend Developer at WebSolutions",
        company: "WebSolutions",
        category: "Web Development",
        salary: "$85k/year",
        location: "Remote",
        jobType: "Full-time",
        description: "WebSolutions is hiring a creative Frontend Developer to build responsive and interactive web interfaces.",
        level: "Mid-level",
        technicalSkills: ["HTML", "CSS", "JavaScript", "React", "Vue.js"]
      },
      {
        id: "003",
        title: "Backend Developer at Cloudify",
        company: "Cloudify",
        category: "Web Development",
        salary: "$100k/year",
        location: "Austin, TX",
        jobType: "Full-time",
        description: "Cloudify is looking for a Backend Developer to handle the server-side logic and database management for various web applications.",
        level: "Mid-level",
        technicalSkills: ["Node.js", "Express", "PostgreSQL", "Redis", "Docker"]
      },
      {
        id: "004",
        title: "Full Stack Developer at DevBase",
        company: "DevBase",
        category: "Web Development",
        salary: "$95k/year",
        location: "Chicago, IL",
        jobType: "Full-time",
        description: "DevBase is searching for a Full Stack Developer to build and maintain complex web applications for its clients.",
        level: "Junior",
        technicalSkills: ["JavaScript", "React", "Node.js", "MongoDB"]
      },
      {
        id: "005",
        title: "Web Developer at CodeWorks",
        company: "CodeWorks",
        category: "Web Development",
        salary: "$75k/year",
        location: "Seattle, WA",
        jobType: "Contract",
        description: "CodeWorks needs a Web Developer to join their team to design, develop, and maintain web solutions for their clients.",
        level: "Mid-level",
        technicalSkills: ["HTML", "CSS", "JavaScript", "PHP", "WordPress"]
      },
      {
        id: "006",
        title: "Data Scientist at DataMinds",
        company: "DataMinds",
        category: "Data Science",
        salary: "$130k/year",
        location: "New York, NY",
        jobType: "Full-time",
        description: "DataMinds is seeking a skilled Data Scientist to join our analytics team. You'll work on complex data problems, develop machine learning models, and provide actionable insights to drive business decisions.",
        level: "Senior",
        technicalSkills: ["Python", "R", "SQL", "Machine Learning", "TensorFlow"]
      },
      {
        id: "007",
        title: "UX/UI Designer at DesignCraft",
        company: "DesignCraft",
        category: "Design",
        salary: "$90k/year",
        location: "Remote",
        jobType: "Contract",
        description: "DesignCraft is looking for a creative UX/UI Designer to help shape the future of our digital products. You'll collaborate with cross-functional teams to create intuitive and visually appealing user interfaces.",
        level: "Mid-level",
        technicalSkills: ["Figma", "Adobe Creative Suite", "Sketch", "Prototyping"]
      },
      {
        id: "008",
        title: "Mobile App Developer at AppWizards",
        company: "AppWizards",
        category: "Mobile Development",
        salary: "$95k/year",
        location: "Seattle, WA",
        jobType: "Full-time",
        description: "AppWizards is seeking a talented Mobile App Developer to create innovative and user-friendly mobile applications. You'll be responsible for developing and maintaining both iOS and Android apps using cross-platform technologies.",
        level: "Junior",
        technicalSkills: ["React Native", "Flutter", "JavaScript", "Swift", "Kotlin"]
      },
      {
        id: "009",
        title: "DevOps Engineer at CloudScale",
        company: "CloudScale",
        category: "DevOps",
        salary: "$110k/year",
        location: "Austin, TX",
        jobType: "Full-time",
        description: "CloudScale is looking for a DevOps Engineer to help streamline our development and deployment processes. You'll work on automating infrastructure, improving CI/CD pipelines, and ensuring system reliability and scalability.",
        level: "Mid-level",
        technicalSkills: ["Docker", "Kubernetes", "Jenkins", "AWS", "Terraform"]
      },
      {
        id: "010",
        title: "Product Manager at InnovateHQ",
        company: "InnovateHQ",
        category: "Management",
        salary: "$105k/year",
        location: "Los Angeles, CA",
        jobType: "Full-time",
        description: "InnovateHQ is seeking a Product Manager to lead the strategy and development of new products in the tech space.",
        level: "Senior",
        technicalSkills: ["Agile", "Scrum", "JIRA", "Product Roadmapping"]
      },
      {
        id: "011",
        title: "Software Engineer at RoboWorks",
        company: "RoboWorks",
        category: "Software Engineering",
        salary: "$120k/year",
        location: "Boston, MA",
        jobType: "Full-time",
        description: "RoboWorks is looking for a Software Engineer to work on robotics software solutions and implement machine learning algorithms for autonomous systems.",
        level: "Senior",
        technicalSkills: ["C++", "Python", "ROS", "Machine Learning"]
      },
      {
        id: "012",
        title: "AI Engineer at DeepTech",
        company: "DeepTech",
        category: "AI",
        salary: "$150k/year",
        location: "San Francisco, CA",
        jobType: "Full-time",
        description: "DeepTech is seeking an AI Engineer to develop cutting-edge AI solutions for various industries.",
        level: "Senior",
        technicalSkills: ["Python", "TensorFlow", "PyTorch", "Deep Learning"]
      },
      {
        id: "013",
        title: "IT Support Specialist at NetFix",
        company: "NetFix",
        category: "IT Support",
        salary: "$60k/year",
        location: "Chicago, IL",
        jobType: "Full-time",
        description: "NetFix is seeking an IT Support Specialist to provide technical assistance and resolve system issues.",
        level: "Junior",
        technicalSkills: ["Windows", "Linux", "Networking", "Troubleshooting"]
      },
      {
        id: "014",
        title: "Marketing Specialist at AdMinds",
        company: "AdMinds",
        category: "Marketing",
        salary: "$70k/year",
        location: "Remote",
        jobType: "Full-time",
        description: "AdMinds is looking for a Marketing Specialist to develop and execute digital marketing campaigns.",
        level: "Mid-level",
        technicalSkills: ["SEO", "Google Analytics", "Content Creation", "Social Media"]
      },
      {
        id: "015",
        title: "Game Developer at FunSoft",
        company: "FunSoft",
        category: "Game Development",
        salary: "$90k/year",
        location: "Los Angeles, CA",
        jobType: "Full-time",
        description: "FunSoft is hiring a Game Developer to create engaging 3D games using Unity and Unreal Engine.",
        level: "Mid-level",
        technicalSkills: ["Unity", "C#", "Unreal Engine", "3D Modeling"]
      },
      {
        id: "016",
        title: "Cybersecurity Analyst at SecureIT",
        company: "SecureIT",
        category: "Cybersecurity",
        salary: "$105k/year",
        location: "San Diego, CA",
        jobType: "Full-time",
        description: "SecureIT is seeking a Cybersecurity Analyst to monitor and protect systems from cyber threats.",
        level: "Senior",
        technicalSkills: ["Firewalls", "Intrusion Detection", "SIEM", "Penetration Testing"]
      },
      {
        id: "017",
        title: "Database Administrator at SQLPro",
        company: "SQLPro",
        category: "Database Administration",
        salary: "$95k/year",
        location: "Remote",
        jobType: "Full-time",
        description: "SQLPro is seeking a Database Administrator to manage, optimize, and secure SQL databases.",
        level: "Mid-level",
        technicalSkills: ["SQL", "MySQL", "Database Tuning", "Backup and Recovery"]
      },
      {
        id: "018",
        title: "Cloud Architect at CloudScale",
        company: "CloudScale",
        category: "Cloud Engineering",
        salary: "$140k/year",
        location: "Remote",
        jobType: "Full-time",
        description: "CloudScale is seeking a Cloud Architect to design and manage scalable cloud infrastructures for clients.",
        level: "Senior",
        technicalSkills: ["AWS", "Azure", "Kubernetes", "Cloud Security"]
      },
      {
        id: "019",
        title: "Systems Engineer at TechForce",
        company: "TechForce",
        category: "Systems Engineering",
        salary: "$110k/year",
        location: "Boston, MA",
        jobType: "Full-time",
        description: "TechForce is seeking a Systems Engineer to design, implement, and maintain systems infrastructure.",
        level: "Mid-level",
        technicalSkills: ["Linux", "Windows Server", "Networking", "VMware"]
      },
      {
        id: "020",
        title: "Machine Learning Engineer at AI Innovations",
        company: "AI Innovations",
        category: "Machine Learning",
        salary: "$125k/year",
        location: "Remote",
        jobType: "Full-time",
        description: "AI Innovations is seeking a Machine Learning Engineer to build and optimize machine learning models for real-world applications.",
        level: "Senior",
        technicalSkills: ["Python", "PyTorch", "TensorFlow", "NLP"]
      }
    ]
  };
  
  export default jobsData;